library(dslabs)
data("gapminder")
length(levels(gapminder$region))
gapminder <- gapminder %>% mutate(dollars_per_day = gdp/population/365)
past_year=1970
p <- gapminder %>% filter(year==past_year &!is.na(gdp)) %>% ggplot(aes(region,dollars_per_day))
p+geom_boxplot()
p+geom_boxplot()+theme(axis.text.x = element_text(angle=90,hjust=1))
fac = factor(c("Asia","Asia","West","West","West"))
levels(fac)
value <- c(10,11,12,6,4)
fac1 <- reorder(fac,value,FUN=mean)
levels(fac1)
p <- gapminder %>% filter(year==past_year & !is.na(gdp)) %>% mutate(region=reorder(region,dollars_per_day,FUN=median))%>%
  ggplot(aes(region,dollars_per_day,fill=continent))+geom_boxplot()+theme(axis.text.x = element_text(angle=90,hjust=1))+xlab("")
p+scale_y_continuous(trans="log2")+geom_point(show.legend = FALSE)